all: test1

test1: a4_superheroLookupSystem.cpp a4_superherolib.cpp a4_superheroList.cpp
	g++ -Wall -std=c++11 -o test1 a4_superheroLookupSystem.cpp a4_superherolib.cpp a4_superheroList.cpp

clean:
	rm -f test1
