all: reallocdemo measure_time random_ar get_name_wrong get_name main

reallocdemo: reallocdemo.c
	gcc -Wall -std=c99 -o reallocdemo reallocdemo.c

measure_time: measure_time.c
	gcc -Wall -std=c99 -o measure_time measure_time.c

random_ar: random_ar.c
	gcc -Wall -std=c99 -o random_ar random_ar.c

get_name_wrong: get_name_wrong.c
	gcc -Wall -std=c99 -o get_name_wrong get_name_wrong.c

get_name: get_name.c
	gcc -Wall -std=c99 -o get_name get_name.c

main: main.c
	gcc -Wall -std=c99 -o main main.c
